# Generated by Django 5.2 on 2025-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_load_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Тегло или количество (напр. в кг)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'гр'), ('l', 'литра'), ('pcs', 'брой')], default='kg', help_text='Мярка за тегло/обем', max_length=10),
        ),
    ]
